---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: activity-tracker
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: allow-crosscom-{{ include "common.names.fullname" . }}-activity-tracker
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: activity-tracker
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
    - protocol: TCP
      port: {{ .Values.service.l2pport }}
    - protocol: UDP
      port: {{ .Values.service.l2pport }}
    from:
      - namespaceSelector:
          matchLabels:
            name: {{ .Release.Namespace }}
