{{- if (not .Values.reqbaz.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/component: reqbaz
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
{{ toYaml .Values.reqbaz.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.reqbaz.persistence.size | quote }}
{{- if .Values.reqbaz.persistence.storageClass }}
{{- if (eq "-" .Values.reqbaz.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.reqbaz.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end -}}
