apiVersion: v1
kind: Service
metadata:
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: reqbaz
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ include "common.names.fullname" . }}-reqbaz
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.reqbaz.service.type }}
  {{- if (or (eq .Values.reqbaz.service.type "LoadBalancer") (eq .Values.reqbaz.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.reqbaz.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.reqbaz.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.reqbaz.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.reqbaz.service.type "LoadBalancer") (not (empty .Values.reqbaz.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.reqbaz.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.reqbaz.service.port }}
      protocol: TCP
    - name: las2peer
      port: {{ .Values.reqbaz.service.l2pport }}
      protocol: TCP
    - name: las2peer-pastry
      port: {{ .Values.reqbaz.service.l2pport }}
      protocol: UDP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: reqbaz
